import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import IpfsComponent from '../components/ipfs'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [state, setState] = useState(null)

  function handleChange(event) {
    setState(() => event.target.files[0])
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div>
          <input type="file" res="state" onChange={handleChange} />
        </div>
        <IpfsComponent state={state} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
